/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recipesearch;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import se.chalmers.ait.dat215.lab2.Recipe;

/**
 *
 * @author amandajonsson
 */
public class ResultView extends javax.swing.JPanel {

    List <JPanel> recipePanels;
    
    /**
     * Creates new form ResultView
     */
    public ResultView(List <Recipe> recipes) {
        initComponents();
        recipePanels = new ArrayList(recipes.size());
        for(Recipe recipe : recipes) {
            JPanel tmp= new SingleRecipeRowPanel(recipe);
            recipePanels.add(tmp);
            mainScrollPane.add(tmp);
            
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        cuisineCombo = new javax.swing.JComboBox<>();
        timeTextLabel = new javax.swing.JLabel();
        cuisinTextLabel = new javax.swing.JLabel();
        timeCombo = new javax.swing.JComboBox<>();
        mainIngTextLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        priceTextLabel = new javax.swing.JLabel();
        mainIngCombo = new javax.swing.JComboBox<>();
        diffCombo = new javax.swing.JComboBox<>();
        diffTextLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        mainScrollPane = new javax.swing.JScrollPane();

        setPreferredSize(new java.awt.Dimension(900, 500));
        setSize(new java.awt.Dimension(900, 500));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 150));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cuisineCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sverige", "Grekland", "Indien", "Asien", "Afrika", "Frankrike" }));
        cuisineCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuisineComboActionPerformed(evt);
            }
        });
        jPanel3.add(cuisineCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 123, -1));

        timeTextLabel.setText("Maxtid");
        jPanel3.add(timeTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        cuisinTextLabel.setText("Kök");
        jPanel3.add(cuisinTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        timeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140" }));
        timeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeComboActionPerformed(evt);
            }
        });
        jPanel3.add(timeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        mainIngTextLabel.setText("Huvudingrediens");
        jPanel3.add(mainIngTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        priceTextField.setText("Skriv in ett heltal");
        jPanel3.add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel18.setText("RECEPT");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 8, -1, -1));

        priceTextLabel.setText("Maxpris");
        jPanel3.add(priceTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, -1, -1));

        mainIngCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kött ", "Fisk", "Kyckling", "Vegetarisk" }));
        jPanel3.add(mainIngCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 136, -1));

        diffCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lätt", "Medel", "Svår" }));
        jPanel3.add(diffCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        diffTextLabel.setText("Svårighetsgrad");
        jPanel3.add(diffTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jButton2.setText("SÖK");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 227, -1));

        add(jPanel3, java.awt.BorderLayout.NORTH);

        mainScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        mainScrollPane.setMaximumSize(new java.awt.Dimension(900, 32767));
        mainScrollPane.setMinimumSize(new java.awt.Dimension(900, 350));
        mainScrollPane.setPreferredSize(new java.awt.Dimension(900, 350));
        add(mainScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cuisineComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuisineComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuisineComboActionPerformed

    private void timeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuisinTextLabel;
    private javax.swing.JComboBox<String> cuisineCombo;
    private javax.swing.JComboBox<String> diffCombo;
    private javax.swing.JLabel diffTextLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> mainIngCombo;
    private javax.swing.JLabel mainIngTextLabel;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel priceTextLabel;
    private javax.swing.JComboBox<String> timeCombo;
    private javax.swing.JLabel timeTextLabel;
    // End of variables declaration//GEN-END:variables
}
